lib/zrl_web/router.ex
    post("/change/loco/driver/status", LocoDriverController, :change_status)
    delete("/delete/loco/driver", LocoDriverController, :delete)
  end

  scope "/", ZrlWeb do
    pipe_through([:session])
    get("/forgort/password", UserController, :forgot_password)
    post("/confirmation/token", UserController, :token)
    get("/reset/password", UserController, :reset_password)
    post("/reset/password", UserController, :reset_password)
    get("/token/verification", SessionController, :entrust_token)
    post("/token/verification", SessionController, :confirm_token)
    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser])
    get("/signout", SessionController, :signout)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])
    get("/movement", MovementController, :movement)
    post("/movement", MovementController, :movement)
    get("/new/movement/order", MovementController, :movement_draft)
    get("/movement/order/verification/batch", MovementController, :movement_verification_batch)
    get("/train/intransit", MovementController, :movement_intransit_batch)
    get("/detached/wagons", MovementController, :movement_detached_batch)
    post("/attach/wagons", MovementController, :attach_detected_wagons)
    post("/mark/train/arrived", MovementController, :mark_train_arrived)
    get("/verify/movement/order", MovementController, :verify_movement)
    post("/verify/movement/order", MovementController, :verify_movement)
    post("/submit/movement/entries", MovementController, :submit_movement)
    get("/submit/movement/entries", MovementController, :submit_movement)
    get("/approve/movement/entries", MovementController, :approve_movement)
    post("/approve/movement/entries", MovementController, :approve_movement)
    post("/create/movement/order", MovementController, :create_movement)
    get("/create/movement/order", MovementController, :create_movement)
    post("/reject/movement/entries", MovementController, :reject_movement)
    get("/reject/movement/entries", MovementController, :rejected_movement)
    post("/discard/movement/entries", MovementController, :discard_movement)
    get("/new/movement", MovementController, :create_movement_batch)
    get("/movement/draft/:batch_id/entries", MovementController, :movement_draft_entries)
    get("/movement/batch/entries", MovementController, :movement_batch_entries)

    get(
      "/movement/batch/:batch_id/verification/entries",
      MovementController,
      :movement_verification_entries
    )

    get(
      "/intransit/:batch_id/train",
      MovementController,
      :movement_intransit_entries
    )

    get(
      "/detached/:batch_id/wagons",
      MovementController,
      :movement_detached_entries
    )

    get(
      "/intransit/:train_no/train/attachment",
      MovementController,
      :intransit_train_attachment
    )

    get(
      "/movement/:batch_id/pending/entries",
      MovementController,
      :movement_pending_entries
    )

    post(
      "/add/wagons/instransit/train",
      MovementController,
      :train_attachment
    )

    post("/movement/batch/entries/lookup", MovementController, :movement_batch_entries_lookup)
    get("/display/movement/entries", MovementController, :display_movement_details)
    get("/movenment/verification", MovementController, :consignment_verification)
    get("/movement/report/batch", MovementController, :movement_report_batch)
    get("/movement/movement/haulage/report", MovementController, :movement_haulage_report)

    get(
      "/movement/movement/customer/based/report",
      MovementController,
      :movement_customer_based_report
    )

    post("/movement/order/report/entries", MovementController, :movement_report_lookup)
    post("/movement/order/report/batch/entries", MovementController, :report_batch_entries_lookup)
    post("/movement/report/entry/lookup", MovementController, :movement_report_entry_lookup)
    get("/movement/order/report/batch/entries", MovementController, :report_batch_entries)
    get("/download/movement/batch/report/excel", MovementController, :excel_exp)
    post("/movement/monthly/income/summary/report", MovementController, :monthly_income_summary)
    get("/movement/monthly/income/summary/report", MovementController, :monthly_income_summary)

    post(
      "/create/movement/order/without/consignment",
      MovementController,
      :movement_without_consignment
    )

    get(
      "/create/movement/order/without/consignment",
      MovementController,
      :movement_without_consignment
    )

    get(
      "/movement/order/without/consignment/entries",
      MovementController,
      :movement_without_congnmt_batch
    )

    get("/modify/movement/batch/entries", MovementController, :edit_movement_entries)
    get("/modify/movement/:batch/batch/entries", MovementController, :edit_movement_entries)
    post("/movement/item/lookup", MovementController, :movement_item_lookup)
    post("/update/movement/batch/item", MovementController, :update_movement_item)
    post("/update/movement/entries", MovementController, :update_movement)
    get("/movement/pending/approval/entries", MovementController, :movement_pending_approval)
    get("/movement/search/locono", MovementController, :search_loco_number)
    get("/movement/search/station", MovementController, :search_station)
    get("/movement/station/owner", MovementController, :lookup_stn_owner)
    post("/movement/station/owner", MovementController, :lookup_stn_owner)
    get("/movement/reconciliation/report", MovementController, :mvt_recon_report)
    get("/movement/wagon/querry/report", MovementController, :mvt_wagon_querry_report)
    get("/new/works/order", MovementController, :works_order)
    post("/new/works/order", MovementController, :create_works_order)
    get("/works/order/report", MovementController, :works_order_report)
    post("/works/order/item/lookup", MovementController, :works_order_lookup)
    post("/detach/train/wagon", MovementController, :detach_wagon)
    get("/works/order/:id/file", MovementController, :works_order_pdf)
    post("/find/invoice/no", MovementController, :invoice_lookup)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])
    get("/new/wagon/tracking", WagonTrackingController, :index)
    post("/create/new/wagon/tracking", WagonTrackingController, :create)
    get("/create//new/wagon/tracking", WagonTrackingController, :create)
    post("/wagon/tracking/entries", WagonTrackingController, :view_wagon_tracker_entries)
    get("/view/wagon/tracking", WagonTrackingController, :view_wagon_tracker)
    get("/view/wagon/tracker", WagonTrackingController, :view_wagon_tracker_by_id)
    get("/wagon/position/report", WagonTrackingController, :view_wagon_position_report)
    post("/wagon/position/tracker/entries", WagonTrackingController, :view_wagon_position_entries)
    get("/wagon/position/tracker/entries", WagonTrackingController, :view_wagon_position_entries)
    get("/wagon/allocation/report", WagonTrackingController, :wagon_allocation_report)
    get("/wagon/summary/report", WagonTrackingController, :wagon_summary_report)

    post(
      "/wagon/allocation/tracker/entries",
      WagonTrackingController,
      :view_wagon_allocation_entries
    )

    get(
      "/wagon/allocation/tracker/entries",
      WagonTrackingController,
      :view_wagon_allocation_entries
    )

    get("/wagon/yard/position/report", WagonTrackingController, :view_wagon_yard_position_report)

    post(
      "/wagon/yard/position/entries",
      WagonTrackingController,
      :view_wagon_yard_position_entries
    )

    get(
      "/wagon/daily/position/report",
      WagonTrackingController,
      :view_wagon_daily_position_report
    )

    get("/wagon/delayed/report", WagonTrackingController, :view_wagon_delayed_report)

    post(
      "/wagon/daily/position/entries",
      WagonTrackingController,
      :view_wagon_daily_position_entries
    )

    post("/wagon/delayed/entries", WagonTrackingController, :view_wagon_delayed_entries)
    get("/wagon/condition/report", WagonTrackingController, :view_wagon_by_condition_report)
    post("/wagon/by/condition/entries", WagonTrackingController, :view_wagon_by_condition_entries)
    get("/daily/wagon/position", WagonTrackingController, :wagon_position)
    get("/delayed/wagon", WagonTrackingController, :list_wagon_delayed)
    post("/delayed/wagon", WagonTrackingController, :list_wagon_delayed)
    post("/wagon/bad/order/average/report", WagonTrackingController, :bad_order_average_lookup)
    get("/wagon/bad/order/average/report", WagonTrackingController, :bad_order_average_lookup)

    get(
      "/delayed/wagon/summary/report/pdf",
      WagonTrackingController,
      :delayed_wagons_generate_pdf
    )

    get("/wagon/summary/report/pdf", WagonTrackingController, :generate_wagon_summary_pdf)

    get(
      "/export/delayed/wagon/summary/report/pdf",
      WagonTrackingController,
      :delayed_wagons_generate_copy_pdf
    )

    get("/edit/wagon/tracker/details", WagonTrackingController, :edit_wagon_tracker_by_id)
    post("/wagon/bad/order/entries", WagonTrackingController, :bad_order_average_entries)
    get("/wagon/bad/order/entries", WagonTrackingController, :bad_order_average_entries)
    get("/bulk/wagon/tracking", WagonTrackingController, :bulk_tracking)
    post("/bulk/wagon/tracking", WagonTrackingController, :handle_bulk_upload)
    get("/bulk/wagon/tracking/upload/errors", WagonTrackingController, :file_upload_errors)
    get("/download/wagon/tracking/report/excel", WagonTrackingController, :wagon_tracking_exp)
    post("/movement/train/lookup", WagonTrackingController, :mvt_train_lookup)
    post("/save/new/wagon/tracker", WagonTrackingController, :save_tracker)
    get("/station/search", WagonTrackingController, :wagon_stn_search)
    get("/spare/search", WagonTrackingController, :wagon_spare_search)
  end

  scope "/", ZrlWeb do

lib/zrl/consignments.ex
defmodule Zrl.Consignments do
  @moduledoc """
  The Consignments context.
  """

  import Ecto.Query, warn: false
  alias Zrl.Repo

  alias Zrl.Order.Consignment

  @doc """
  Returns the list of tbl_consignments.
  
  ## Examples
  
      iex> list_tbl_consignments()
      [%Consignment{}, ...]
  
  """
  def list_tbl_consignments do
    Repo.all(Consignment)
  end

  # def pending_consign_lookup() do
  #   Consignment
  #   |> where([status: ^"PENDING"])
  #   # |> preload([:consignment])
  #   |> select(
  #   [a],
  #   map(a, [
  #     :capture_date,
  #     :code,
  #     :customer_ref,
  #     :document_date,
  #     :sale_order,
  #     :station_code,
  #     :status,
  #     :vat_amount,
  #     :invoice_no,
  #     :rsz,
  #     :nlpi,
  #     :nll_2005,
  #     :tfr,
  #     :tzr,
  #     :tzr_project,
  #     :additional_chg,
  #     :final_destination_id,
  #     :origin_station_id,
  #     :reporting_station_id,
  #     :commodity_id,
  #     :consignee_id,
  #     :consigner_id,
  #     :customer_id,
  #     :payer_id,
  #     :tarrif_id,
  #     :maker_id,
  #     :wagon_id,
  #     :checker_id,
  #     :comment,
  #     :capacity_tonnes,
  #     :actual_tonnes,
  #     :tariff_tonnage,
  #     :container_no,
  #     consignment: [:consignment_id]

  #     ])
  #   )
  #   |> Repo.all()
  # end

  @doc """
  Gets a single consignment.
  
  Raises `Ecto.NoResultsError` if the Consignment does not exist.
  
  ## Examples
  
      iex> get_consignment!(123)
      %Consignment{}
  
      iex> get_consignment!(456)
      ** (Ecto.NoResultsError)
  
  """
  def get_consignment!(id), do: Repo.get!(Consignment, id)

  @doc """
  Creates a consignment.
  
  ## Examples
  
      iex> create_consignment(%{field: value})
      {:ok, %Consignment{}}
  
      iex> create_consignment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}
  
  """
  def create_consignment(attrs \\ %{}) do
    %Consignment{}
    |> Consignment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a consignment.
  
  ## Examples
  
      iex> update_consignment(consignment, %{field: new_value})
      {:ok, %Consignment{}}
  
      iex> update_consignment(consignment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}
  
  """
  def update_consignment(%Consignment{} = consignment, attrs) do
    consignment
    |> Consignment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a consignment.
  
  ## Examples
  
      iex> delete_consignment(consignment)
      {:ok, %Consignment{}}
  
      iex> delete_consignment(consignment)
      {:error, %Ecto.Changeset{}}
  
  """
  def delete_consignment(%Consignment{} = consignment) do
    Repo.delete(consignment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking consignment changes.
  
  ## Examples
  
      iex> change_consignment(consignment)
      %Ecto.Changeset{data: %Consignment{}}
  
  """
  def change_consignment(%Consignment{} = consignment, attrs \\ %{}) do
    Consignment.changeset(consignment, attrs)
  end

  def pending_consign_lookup() do
    Consignment
    |> join(:left, [c], w in "tbl_wagon", on: c.wagon_id == w.id)
    |> join(:left, [c, w], cl in "tbl_clients", on: c.consignee_id == cl.id)
    |> join(:left, [c, w, cl], com in "tbl_commodity", on: c.commodity_id == com.id)
    |> join(:left, [c, w, cl, com], st in "tbl_stations", on: c.origin_station_id == st.id)
    |> where([c, w], c.status == "PENDING")
    |> select([c, w, cl, com, st], %{
      id: c.id,
      wagon: w.code,
      consignee: cl.client_name,
      consigner: cl.client_name,
      description: com.description,
      container_no: c.container_no,
      sale_order: c.sale_order,
      station_code: c.station_code,
      payer: cl.client_name,
      status: c.status,
      capture_date: c.capture_date,
      origin_station: st.acronym,
      final_destination: st.acronym
    })
    |> Repo.all()
  end
end

lib/zrl_web/templates/consignment/consignment_batch_report.html.eex
<div class="m-subheader" id="consignment-list-report-link" style="padding: 0px 0px 0 0px;">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator"> Consignment List</h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<%= Routes.user_path(@conn, :dashboard) %>" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text">Reports</span>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text"> Consignment List </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<br><br>

<div class="m-portlet m-portlet--mobile">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                   Consignment List
                </h3>
            </div>
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <%= if Zrl.Accounts.User.has_role?(@user, :consignment, :new_consignment) do %>
                    <li class="m-portlet__nav-item">
                        <a href="<%= Routes.consignment_path(@conn, :new_consignment) %>" class="btn btn-brand m-btn m-btn--custom m-btn--icon m-btn--air">
                            <span>
                                <i class="la la-plus-circle"></i>
                                <span>Add</span>
                            </span>
                        </a>
                    </li>
                <% end %>
                <li class="m-portlet__nav-item"></li>
                 <li class="m-portlet__nav-item">
                    <a href="#" id="download_consignment_report_excel" class="btn btn-success m-btn m-btn--custom m-btn--icon m-btn--air">
                        <span>
                            <i class="fa fa-file-excel"></i>
                            <span>Excel</span>
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <form class="m-form m-form--fit m--margin-bottom-20" id = "consignment_batch_report_form">
            <div class="row m--margin-bottom-20">
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label>Consignment List No:</label>
                    <input type="text" class="form-control m-input clear_form" placeholder="Consignment List" name="consignment_sales_order" id="consignment_sales_order" >
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label>PZ Code:</label>
                    <input type="text" class="form-control m-input clear_form" placeholder="PZ Code"   name="consignment_station_code" id="consignment_station_code">
                    <input type="hidden" id="report_type" name= "report_type" value="CONSIGNMENT_REPORT">
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label for="example-input-small" class="form-label">Reporting Station:</label>
                    <div class="m-input-icon m-input-icon--right">
                        <select  name="consignment_reporting_station" id="consignment_reporting_station" class="form-control ajax-search-wagon-stn clear_form clear_select" required>
                            <option></option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label for="example-input-small" class="form-label">Customer</label>
                    <div class="m-input-icon m-input-icon--right">
                        <select  name="consignment_customer" id="consignment_customer" class="form-control js-search_client-ajax clear_form clear_select" required>
                            <option></option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row m--margin-bottom-20">
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label for="example-input-small" class="form-label">Consignee</label>
                    <div class="m-input-icon m-input-icon--right">
                        <select  name="consignment_consignee" id="consignment_consignee" class="form-control js-search_client-ajax clear_form clear_select" required>
                            <option></option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label for="example-input-small" class="form-label">Payer</label>
                    <div class="m-input-icon m-input-icon--right">
                        <select  name="consignment_payer" id="consignment_payer" class="form-control js-search_client-ajax clear_form clear_select" required>
                            <option></option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label for="example-input-small" class="form-label">Commodity</label>
                    <div class="m-input-icon m-input-icon--right">
                        <select  name="consignment_commodity" id="consignment_commodity" class="form-control js-consign-search-cmmdity clear_form clear_select" required>
                            <option></option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 m--margin-bottom-10-tablet-and-mobile">
                    <label>Created Date:</label>
                    <div class="">
                        <div class="input-daterange input-group" id="m_datepicker_6">
                            <input type="text" class="form-control m-input clear_form" name="from" id="from" placeholder="From" />
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="la la-ellipsis-h"></i></span>
                            </div>
                            <input type="text" class="form-control clear_form" name="to" id="to" placeholder="To" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <button type="button" id="consignment_batch_report_filter" class="btn btn-info m-btn m-btn--icon" id="movement_report_table_filter">
                        <span>
                            <i class="la la-search"></i>
                            <span>Search</span>
                        </span>
                    </button>
                    &nbsp;&nbsp;
                    <button  type="button" id="consignment_reset_report_filter"class="btn btn-metal m-btn m-btn--icon" id="movement_report_reset_filter">
                        <span>
                            <i class="la la-close"></i>
                            <span>Reset</span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="m-separator m-separator--md m-separator--dashed"></div>
        </form>
        <!--begin: Datatable -->
        <table class="table table-striped m-table table-sm" id="dt-consignment-report-batch-entries">
        <input type="hidden" id="csrf" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token()%>">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>PZ Code</th>
                    <th>Capture Date</th>
                    <th>Consignee</th>
                    <th>Payer</th>
                    <th>Commodity</th>
                    <th>Origin Station</th>
                    <th>Tariff Origin</th>
                    <th style="width: 70px;">Action</th>
                </tr>
            </thead>
        </table>
    </div>
</div>

lib/zrl_web/templates/consignment/haulage_invoice.html.eex
<div class="m-subheader" id="consignment-haulage-invoice-report-link" style="padding: 0px 0px 0 0px;">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">Haulage Invoice</h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<%= Routes.user_path(@conn, :dashboard) %>" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text">Haulage Invoice</span>
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" m-dropdown-toggle="hover" aria-expanded="true">
                <a href="#" class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--outline-2x m-btn--air m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                    <i class="la la-plus m--hide"></i>
                    <i class="la la-ellipsis-h"></i>
                </a>
                <div class="m-dropdown__wrapper" style="z-index: 101;">
                    <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust" style="left: 30; right: 21.5px;"></span>
                    <div class="m-dropdown__inner">
                        <div class="m-dropdown__body">
                            <div class="m-dropdown__content-sm" >
								<ul class="m-nav">
									<li class="m-nav__section m-nav__section--first">
										<span class="m-nav__section-text">Quick Actions</span>
									</li>
									<li class="m-nav__item">
										<a href="#"  data-target="#onboardingWideFormModal" data-toggle="modal" class="m-nav__link">
											<i class="m-nav__link-icon flaticon-search"></i>
											<span class="m-nav__link-text">Search</span>
										</a>
									</li>
									<li class="m-nav__item">
										<a href="<%= Routes.consignment_path(@conn, :haulage_invoice_generate_pdf, %{end_dt:  @end_date, start_dt: @start_date}) %>" class="m-nav__link">
											<i class="m-nav__link-icon flaticon-download"></i>
											<span class="m-nav__link-text">Generate Pdf</span>
										</a>
									</li>
								</ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br>


<div class="row">
	<div class="col-lg-12">
		<div class="m-portlet">
			<div class="m-portlet__body m-portlet__body--no-padding">
				<div class="m-invoice-2">
					<div class="m-invoice__wrapper">
						<div class="m-invoice__head">
							<div class="m-invoice__container m-invoice__container--centered">
								<div class="m-invoice__logo">
									<div class="row">
										<div class="col-md-3 mt-5">
											<a href="#" style ="cursor:default; text-decoration: none;">
												<h5 style="color: #6f727d; margin-left: 0px">Haulage Invoice</h5>
											</a>
										</div>
										<div class="col-md-6 text-center"><h3><%= @company && @company.company_name %></h3></div>
										<div class="col-md-3 text-right">
											<a href="#">
												<img src="<%= Routes.static_path(@conn, "/images/Logo_mark.png") %>" style="width:55px; height:55px;">
											</a>
										</div>
									</div>
								</div>
								<span class="m-invoice__desc">
									<span><%= @company && @company.company_name %></span>
									<span><%= @company && @company.company_address %></span>
								</span>
								<div class="m-invoice__items" style="padding: 2rem 0 3rem 0;">
									<div class="m-invoice__item"  >
										<span class="m-invoice__text"><%= Timex.format!(Date.from_iso8601!(@start_date),"%A, %B %e, %Y", :strftime) %> To  <%= Timex.format!(Date.from_iso8601!(@end_date),"%A, %B %e, %Y", :strftime) %></span>
									</div>
								</div>
							</div>
						</div>
						<div class="m-invoice__body m-invoice__body--centered">
							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>COMMODITY</th>
											<th>TONNAGE</th>
											<th>TON/KM</th>
											<th>AMOUNT</th>
										</tr>
									</thead>
									<tbody>
										<%= for {transport_type, results} <- @summary do %>
										<tr>
											<td><%= transport_type %></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
										</tr>
										<%= for summary <- results do %>
										<tr>
											<td style=" font-weight: normal !important; text-"><%= summary.commodity_type %></td>
											<td style=" font-weight: normal !important;"><%=  Number.Delimit.number_to_delimited(summary.tonnages || 0, precision: 2) %></td>
											<td style=" font-weight: normal !important;"><%=  Number.Delimit.number_to_delimited(summary.tonnages_per_km || 0, precision: 2)  %></td>
											<td style=" font-weight: normal !important;"><%= "#{summary.currency_symbol} #{ Number.Delimit.number_to_delimited(summary.amount || 0, precision: 2)}"%></td>
										</tr>
										<% end %>
										<tr>
											<td></td>
											<td><%= Number.Delimit.number_to_delimited(hd(results).total_tonnage || 0, precision: 2) %></td>
											<td><%= Number.Delimit.number_to_delimited(hd(results).total_km || 0, precision: 2) %></td>
											<td><%="#{ hd(results).currency_symbol} #{ Number.Delimit.number_to_delimited(hd(results).total_amount || 0, precision: 2)}" %></td>
										</tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
						<div class="m-invoice__footer"    style="margin-top: 2rem;">
							<div class="m-invoice__table  m-invoice__table--centered table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>TOTAL TONNAGES</th>
											<th>TOTAL TON/KM</th>
											<th>TOTAL AMOUNT</th>
										</tr>
									</thead>
									<tbody>
										<tr>

											<td><%= Number.Delimit.number_to_delimited( @total_tonnages || 0, precision: 2) %></td>
											<td><%= Number.Delimit.number_to_delimited( @total_km || 0, precision: 2) %></td>
											<td class="m--font-danger"><%= @total_amount %></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade model_select_2" id="onboardingWideFormModal">
    <div class="modal-dialog modal-lg modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle" style="margin-top:5px; margin-left:20px;">Filter</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
            </div>
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed col-lg-12" action="<%= Routes.consignment_path(@conn, :haulage_invoice) %>" method="POST">
                <input type="hidden" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token()%>">
                <div class="m-portlet__body">

                    <div class="form-group m-form__group row">
                        <div class="col-lg-6">
                            <label>Start Date</label>
                            <div class="m-input-icon m-input-icon--right">
                                <input type="date" class="form-control m-input" name="start_date">
                            </div>
                            <span class="m-form__help">Please select Start date</span>
                        </div>
                        <div class="col-lg-6">
                            <label class="">End Date</label>
                            <div class="m-input-icon m-input-icon--right">
                                <input type="date" class="form-control m-input" name="end_date" required="required">
                            </div>
                            <span class="m-form__help">Please select End date</span>
                        </div>
                    </div>

                </div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
            </form>
        </div>
    </div>
</div>