lib/zrl_web/router.ex
      "/movement/:batch_id/pending/entries",
      MovementController,
      :movement_pending_entries
    )

    post(
      "/add/wagons/instransit/train",
      MovementController,
      :train_attachment
    )

    post("/movement/batch/entries/lookup", MovementController, :movement_batch_entries_lookup)
    get("/display/movement/entries", MovementController, :display_movement_details)
    get("/movenment/verification", MovementController, :consignment_verification)
    get("/movement/report/batch", MovementController, :movement_report_batch)
    get("/movement/movement/haulage/report", MovementController, :movement_haulage_report)

    get(
      "/movement/movement/customer/based/report",
      MovementController,
      :movement_customer_based_report
    )

    post("/movement/order/report/entries", MovementController, :movement_report_lookup)
    post("/movement/order/report/batch/entries", MovementController, :report_batch_entries_lookup)
    post("/movement/report/entry/lookup", MovementController, :movement_report_entry_lookup)
    get("/movement/order/report/batch/entries", MovementController, :report_batch_entries)
    get("/download/movement/batch/report/excel", MovementController, :excel_exp)
    post("/movement/monthly/income/summary/report", MovementController, :monthly_income_summary)
    get("/movement/monthly/income/summary/report", MovementController, :monthly_income_summary)

    post(
      "/create/movement/order/without/consignment",
      MovementController,
      :movement_without_consignment
    )

    get(
      "/create/movement/order/without/consignment",
      MovementController,
      :movement_without_consignment
    )

    get(
      "/movement/order/without/consignment/entries",
      MovementController,
      :movement_without_congnmt_batch
    )

    get("/modify/movement/batch/entries", MovementController, :edit_movement_entries)
    get("/modify/movement/:batch/batch/entries", MovementController, :edit_movement_entries)
    post("/movement/item/lookup", MovementController, :movement_item_lookup)
    post("/update/movement/batch/item", MovementController, :update_movement_item)
    post("/update/movement/entries", MovementController, :update_movement)
    get("/movement/pending/approval/entries", MovementController, :movement_pending_approval)
    get("/movement/search/locono", MovementController, :search_loco_number)
    get("/movement/search/station", MovementController, :search_station)
    get("/movement/station/owner", MovementController, :lookup_stn_owner)
    post("/movement/station/owner", MovementController, :lookup_stn_owner)
    get("/movement/reconciliation/report", MovementController, :mvt_recon_report)
    get("/movement/wagon/querry/report", MovementController, :mvt_wagon_querry_report)
    get("/new/works/order", MovementController, :works_order)
    post("/new/works/order", MovementController, :create_works_order)
    get("/works/order/report", MovementController, :works_order_report)
    post("/works/order/item/lookup", MovementController, :works_order_lookup)
    post("/detach/train/wagon", MovementController, :detach_wagon)
    get("/works/order/:id/file", MovementController, :works_order_pdf)
    post("/find/invoice/no", MovementController, :invoice_lookup)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])
    get("/new/wagon/tracking", WagonTrackingController, :index)
    post("/create/new/wagon/tracking", WagonTrackingController, :create)
    get("/create//new/wagon/tracking", WagonTrackingController, :create)
    post("/wagon/tracking/entries", WagonTrackingController, :view_wagon_tracker_entries)
    get("/view/wagon/tracking", WagonTrackingController, :view_wagon_tracker)
    get("/view/wagon/tracker", WagonTrackingController, :view_wagon_tracker_by_id)
    get("/wagon/position/report", WagonTrackingController, :view_wagon_position_report)
    post("/wagon/position/tracker/entries", WagonTrackingController, :view_wagon_position_entries)
    get("/wagon/position/tracker/entries", WagonTrackingController, :view_wagon_position_entries)
    get("/wagon/allocation/report", WagonTrackingController, :wagon_allocation_report)
    get("/wagon/summary/report", WagonTrackingController, :wagon_summary_report)

    post(
      "/wagon/allocation/tracker/entries",
      WagonTrackingController,
      :view_wagon_allocation_entries
    )

    get(
      "/wagon/allocation/tracker/entries",
      WagonTrackingController,
      :view_wagon_allocation_entries
    )

    get("/wagon/yard/position/report", WagonTrackingController, :view_wagon_yard_position_report)

    post(
      "/wagon/yard/position/entries",
      WagonTrackingController,
      :view_wagon_yard_position_entries
    )

    get(
      "/wagon/daily/position/report",
      WagonTrackingController,
      :view_wagon_daily_position_report
    )

    get("/wagon/delayed/report", WagonTrackingController, :view_wagon_delayed_report)

    post(
      "/wagon/daily/position/entries",
      WagonTrackingController,
      :view_wagon_daily_position_entries
    )

    post("/wagon/delayed/entries", WagonTrackingController, :view_wagon_delayed_entries)
    get("/wagon/condition/report", WagonTrackingController, :view_wagon_by_condition_report)
    post("/wagon/by/condition/entries", WagonTrackingController, :view_wagon_by_condition_entries)
    get("/daily/wagon/position", WagonTrackingController, :wagon_position)
    get("/delayed/wagon", WagonTrackingController, :list_wagon_delayed)
    post("/delayed/wagon", WagonTrackingController, :list_wagon_delayed)
    post("/wagon/bad/order/average/report", WagonTrackingController, :bad_order_average_lookup)
    get("/wagon/bad/order/average/report", WagonTrackingController, :bad_order_average_lookup)

    get(
      "/delayed/wagon/summary/report/pdf",
      WagonTrackingController,
      :delayed_wagons_generate_pdf
    )

    get("/wagon/summary/report/pdf", WagonTrackingController, :generate_wagon_summary_pdf)

    get(
      "/export/delayed/wagon/summary/report/pdf",
      WagonTrackingController,
      :delayed_wagons_generate_copy_pdf
    )

    get("/edit/wagon/tracker/details", WagonTrackingController, :edit_wagon_tracker_by_id)
    post("/wagon/bad/order/entries", WagonTrackingController, :bad_order_average_entries)
    get("/wagon/bad/order/entries", WagonTrackingController, :bad_order_average_entries)
    get("/bulk/wagon/tracking", WagonTrackingController, :bulk_tracking)
    post("/bulk/wagon/tracking", WagonTrackingController, :handle_bulk_upload)
    get("/bulk/wagon/tracking/upload/errors", WagonTrackingController, :file_upload_errors)
    get("/download/wagon/tracking/report/excel", WagonTrackingController, :wagon_tracking_exp)
    post("/movement/train/lookup", WagonTrackingController, :mvt_train_lookup)
    post("/save/new/wagon/tracker", WagonTrackingController, :save_tracker)
    get("/station/search", WagonTrackingController, :wagon_stn_search)
    get("/spare/search", WagonTrackingController, :wagon_spare_search)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])

    get "/view/user/roles", UserRoleController, :index
    get "/new/user/role", UserRoleController, :new
    post "/new/user/role", UserRoleController, :create
    get "/update/user/:id/role", UserRoleController, :edit
    post "/update/user/role", UserRoleController, :update
    delete "/delete/user/role", UserRoleController, :delete
    post "/change/user/role/status", UserRoleController, :change_status
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])

    get "/view/user/regions", UserRegionController, :index
    get "/new/user/region", UserRegionController, :new
    post "/new/user/region", UserRegionController, :create
    get "/update/user/:id/region", UserRegionController, :edit
    post "/update/user/region", UserRegionController, :update
    # get "/system/user/region", UserRegionController, :index
    delete "/delete/user/region", UserRegionController, :delete
    post "/change/user/region/status", UserRegionController, :change_status
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])

    get("/cond/category", ConditionCategoryController, :index)
    post("/new/cond/category", ConditionCategoryController, :create)
    get("/ne/new/cond/category", ConditionCategoryController, :create)
    post("/change/user/cond/category/status", ConditionCategoryController, :change_status)
  end

  scope "/", ZrlWeb do
    pipe_through([:browser, :app])

    get("/consignment", ConsignmentController, :consignment)
    post("/save/consignment/order", ConsignmentController, :save_consignment)
    post("/submit/consignment/order", ConsignmentController, :submit_consignment)
    post("/verify/consignment/order/entries", ConsignmentController, :verification_consignment)
    post("/approve/consignment/order/entries", ConsignmentController, :approval_consignment)
    post("/discard/consignment/order/entries", ConsignmentController, :discard_consignment)
    get("/consignment/order/report/entries", ConsignmentController, :consignment_batch_report)

    post(
      "/consignment/order/report/entries",
      ConsignmentController,
      :consignment_report_batch_lookup
    )

    get(
      "/consignment/sales/order/report/entries",
      ConsignmentController,
      :consignment_batch_entries
    )

    get(
      "/consignment/sales/order/verification/batch",
      ConsignmentController,
      :consignment_verifcation_batches
    )

    post("/consignment/batch/entries", ConsignmentController, :consignment_batch_lookup)

    get(
      "/consignment/sales/order/approval/batch",
      ConsignmentController,
      :consignment_approval_batches
    )

    get(
      "/consignment/sales/order/invoice/batch",
      ConsignmentController,
      :consignment_invoice_batches
    )

    get("/consignment/verification/entries", ConsignmentController, :verify_consignment_entries)

lib/zrl/tracking/wagon_tracking.ex
defmodule Zrl.Tracking.WagonTracking do
  use Ecto.Schema
  use Endon
  import Ecto.Changeset
  alias Zrl.SystemUtilities.TariffLine

  @cast [
    :update_date,
    :departure,
    :arrival,
    :train_no,
    :yard_siding,
    :sub_category,
    :comment,
    :net_ton,
    :bound,
    :allocated_cust_id,
    :user_region_id,
    :on_hire,
    :wagon_id,
    :current_location_id,
    :condition_id,
    :commodity_id,
    :customer_id,
    :origin_id,
    :destination_id,
    :maker_id,
    :checker_id,
    :domain_id,
    :month,
    :year,
    :days_at,
    :total_accum_days,
    :defect_id,
    :file_name,
    :uuid,
    :wagon_code,
    :current_status_code,
    :domain_code,
    :condition_code,
    :tracking_type
  ]

  @required [
    :update_date,
    :departure,
    # :arrival,
    :train_no,
    # :comment,
    # :allocated_to_customer,
    # :hire,
    :wagon_id
    # :current_location_id, :id,
    # :condition_id, :id,
    # :commodity_id, :id,
    # :customer_id,
    # :origin_id, :id,
    # :destination_id, :id,
    # :maker_id, :id,
    # :defect_id, :id
    # :checker_id, :id,
  ]

  @timestamps_opts [autogenerate: {TariffLine.Localtime, :autogenerate, []}]
  schema "tbl_wagon_tracking" do
    field :allocated_to_customer, :string
    field :total_accum_days, :integer, default: 0
    field :arrival, :string
    field :bound, :string
    field :comment, :string
    field :departure, :string
    field :on_hire, :string, default: "N"
    field :net_ton, :decimal
    field :sub_category, :string
    field :train_no, :string
    field :update_date, :date
    field :yard_siding, :string
    field :month, :string
    field :year, :string
    field :file_name, :string
    field :uuid, :string
    field :days_at, :integer, default: 0
    field :wagon_code, :string, virtual: true
    field :current_status_code, :string, virtual: true
    field :domain_code, :string, virtual: true
    field :condition_code, :string, virtual: true
    field :tracking_type, :string, virtual: true
    # field :wagon_id, :id
    # field :current_location_id, :id
    # field :condition_id, :i
    # field :commodity_id, :id
    # field :customer_id, :id
    # field :origin_id, :id
    # field :destination_id, :id
    # field :maker_id, :id
    # field :checker_id, :id

    belongs_to :defects, Zrl.SystemUtilities.Defect, foreign_key: :defect_id, type: :id
    belongs_to :destination, Zrl.SystemUtilities.Station, foreign_key: :destination_id, type: :id
    belongs_to :origin, Zrl.SystemUtilities.Station, foreign_key: :origin_id, type: :id

    belongs_to :location, Zrl.SystemUtilities.Station,
      foreign_key: :current_location_id,
      type: :id

    belongs_to :commodity, Zrl.SystemUtilities.Commodity, foreign_key: :commodity_id, type: :id
    belongs_to :customer, Zrl.Accounts.Clients, foreign_key: :customer_id, type: :id

    belongs_to :allocated_customer, Zrl.Accounts.Clients,
      foreign_key: :allocated_cust_id,
      type: :id

    belongs_to :maker, Zrl.Accounts.User, foreign_key: :maker_id, type: :id
    belongs_to :checker, Zrl.Accounts.User, foreign_key: :checker_id, type: :id
    belongs_to :wagon, Zrl.SystemUtilities.Wagon, foreign_key: :wagon_id, type: :id
    belongs_to :condition, Zrl.SystemUtilities.Condition, foreign_key: :condition_id, type: :id
    belongs_to :domain, Zrl.SystemUtilities.Domain, foreign_key: :domain_id, type: :id
    belongs_to :user_region, Zrl.Accounts.UserRegion, foreign_key: :user_region_id, type: :id

    timestamps()
  end

  @doc false
  def changeset(wagon_tracking, attrs) do
    wagon_tracking
    |> cast(attrs, @cast)
    # |> find_wagon_by_code()
    # |> find_current_status_by_code()
    # |> find_domain_by_code()
    # |> find_conditin_by_code()
    |> validate_required(@required)
    |> does_movement_exist?()
    |> unique_constraint(:update_date, name: :unique_wagon_tracker, message: "already exists")
  end

  defp does_movement_exist?(%Ecto.Changeset{valid?: true} = changeset) do
    train_no = get_field(changeset, :train_no)
    wagon_id = get_field(changeset, :wagon_id)

    case Zrl.Order.search_for_train_list_entry(wagon_id, train_no) do
      nil ->
        # add_error(changeset, :train_no, " \"#{train_no}\" does not exist")
        does_train_exist?(train_no, changeset)

      movement ->
        change(changeset,
          commodity_id: movement.commodity_id,
          customer_id: movement.customer_id,
          origin_id: movement.origin_station_id,
          destination_id: movement.destin_station_id
        )
    end
  end

  defp does_movement_exist?(changeset), do: changeset

  defp does_train_exist?(train_no, changeset) do
    case Zrl.Order.search_for_train(train_no) do
      nil ->
        add_error(changeset, :train_no, " \"#{train_no}\" does not exist")

      movement ->
        tracking_type(changeset, movement)
    end
  end

  defp tracking_type(changeset, movement) do
    case get_field(changeset, :tracking_type) do
      "SINGLE" ->
        change(changeset,
          origin_id: movement.origin_station_id,
          destination_id: movement.destin_station_id
        )

      _ ->
        changeset
    end
  end

  # defp find_wagon_by_code(
  #        %Ecto.Changeset{valid?: true, changes: %{wagon_code: wagon_code}} = changeset
  #      ) do
  #   case Zrl.SystemUtilities.wagon_lookup(wagon_code) do
  #     nil ->
  #       add_error(changeset, :wagon_code, " \"#{wagon_code}\" does not exist")

  #     wagon ->
  #       change(changeset, wagon_id: wagon.id)
  #   end
  # end

  # defp find_wagon_by_code(changeset), do: changeset

  # defp find_current_status_by_code(
  #        %Ecto.Changeset{valid?: true, changes: %{current_status_code: code}} = changeset
  #      ) do
  #   case Zrl.SystemUtilities.wagon_status_lookup(code) do
  #     nil ->
  #       add_error(changeset, :current_status_code, " \"#{code}\" does not exist")

  #     current_status ->
  #       change(changeset, departure: to_string(current_status.id))
  #   end
  # end

  # defp find_current_status_by_code(changeset), do: changeset

  # defp find_domain_by_code(
  #        %Ecto.Changeset{valid?: true, changes: %{domain_code: code}} = changeset
  #      ) do
  #   case Zrl.SystemUtilities.domain_lookup(code) do
  #     nil ->
  #       add_error(changeset, :domain_code, " \"#{code}\" does not exist")

  #     domain ->
  #       change(changeset, domain_id: domain.id)
  #   end
  # end

  # defp find_domain_by_code(changeset), do: changeset

  # defp find_conditin_by_code(
  #        %Ecto.Changeset{valid?: true, changes: %{condition_code: code}} = changeset
  #      ) do
  #   case Zrl.SystemUtilities.wagon_condition_lookup(code) do
  #     nil ->
  #       add_error(changeset, :condition_code, " \"#{code}\" does not exist")

  #     condition ->
  #       change(changeset, condition_id: condition.id)
  #   end
  # end

  # defp find_conditin_by_code(changeset), do: changeset
end

lib/zrl_web/templates/wagon_tracking/file_upload_errors.html.eex
<div class="m-subheader" id="wagon-tracking-upload-errors-link" style="padding: 0px 0px 0 0px;">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">File Upload Errors</h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<%= Routes.user_path(@conn, :dashboard) %>" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text">Wagon Tracking</span>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text">File Upload Errors</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<br>

<!--begin::Portlet-->
<div class="m-portlet">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon m--hide"><i class="la la-gear"></i></span>
                <h3 class="m-portlet__head-text">
                   Upload Errors
                </h3>
            </div>
        </div>
    </div>

    <!--begin::Form-->
    <div class="m-portlet__body">
        <!--begin: Datatable -->
        <table class="table table-striped m-table table-sm" role="grid" id="dt_wagon_bulk_file_errors">
        <input type="hidden" id="csrf" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token()%>">
            <thead>
                <tr>
                    <th>S/N</th>
                    <th>Filename</th>
                    <th>Error</th>
                </tr>
            </thead>
            <tbody>
                <%= for file_error <- @file_errors do %>
                    <tr>
                        <td><%= file_error.col_index %></td>
                        <td><%= String.replace("#{file_error.filename}", ".xlsx", "") %></td>
                        <td><%= file_error.error_msg %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<!--end::Portlet-->

lib/zrl_web/templates/wagon_tracking/wagon_delayed_summary.html.eex
<div class="m-subheader" id="wagon-delayed-report-link" style="padding: 0px 0px 0 0px;">
    <div class="d-flex align-items-center">
        <div class="mr-auto">
            <h3 class="m-subheader__title m-subheader__title--separator">Delayed Summary</h3>
            <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                <li class="m-nav__item m-nav__item--home">
                    <a href="<%= Routes.user_path(@conn, :dashboard) %>" class="m-nav__link m-nav__link--icon">
                        <i class="m-nav__link-icon la la-home"></i>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="" class="m-nav__link">
                        <span class="m-nav__link-text">Wagon Tracking</span>
                    </a>
                </li>
                <li class="m-nav__separator">-</li>
                <li class="m-nav__item">
                    <a href="#" class="m-nav__link">
                        <span class="m-nav__link-text">Delayed Summary</span>
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" m-dropdown-toggle="hover" aria-expanded="true">
                <a href="#" class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--outline-2x m-btn--air m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                    <i class="la la-plus m--hide"></i>
                    <i class="la la-ellipsis-h"></i>
                </a>
                <div class="m-dropdown__wrapper" style="z-index: 101;">
                    <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust" style="left: 30; right: 21.5px;"></span>
                    <div class="m-dropdown__inner">
                        <div class="m-dropdown__body">
                            <div class="m-dropdown__content-sm" >
								<ul class="m-nav">
									<li class="m-nav__section m-nav__section--first">
										<span class="m-nav__section-text">Quick Actions</span>
									</li>
									<li class="m-nav__item">
										<a href="#"  data-target="#date_filter" data-toggle="modal" class="m-nav__link">
											<i class="m-nav__link-icon flaticon-search"></i>
											<span class="m-nav__link-text">Search</span>
										</a>
									</li>
									<li class="m-nav__item">
										<a href="<%= Routes.wagon_tracking_path(@conn, :delayed_wagons_generate_pdf, %{end_dt:  @end_date, start_dt: @start_date}) %>" class="m-nav__link">
											<i class="m-nav__link-icon flaticon-download"></i>
											<span class="m-nav__link-text">Generate Pdf</span>
										</a>
									</li>
								</ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br>

<div class="row">
	<div class="col-lg-12">
		<div class="m-portlet">
			<div class="m-portlet__body m-portlet__body--no-padding">
				<div class="m-invoice-2">
					<div class="m-invoice__wrapper">
						<div class="m-invoice__head">
							<div class="m-invoice__container m-invoice__container--centered">
								<div class="m-invoice__logo">
									<div class="row">
										<div class="col-md-3 mt-5">
											<a href="#" style="cursor:default; text-decoration: none;">
												<h5 style="color: #6f727d; margin-left: 0px">Delayed Summary</h5>
											</a>
										</div>
										<div class="col-md-6 text-center"><h3><%= @company && @company.company_name %></h3></div>
										<div class="col-md-3 text-right">
											<a href="#">
												<img src="<%= Routes.static_path(@conn, "/images/Logo_mark.png") %>" style="width:55px; height:55px;">
											</a>
										</div>
									</div>
								</div>
								<span class="m-invoice__desc">
									<span><%= @company && @company.company_name %></span>
									<span><%= @company && @company.company_address %></span>
								</span>

								<div class="m-invoice__items" style="padding: 2rem 0 3rem 0;">
									<div class="m-invoice__item"  >
										<%# <span class="m-invoice__subtitle">DATA</span> %>
										<span class="m-invoice__text"><%= Timex.format!(Date.from_iso8601!(@start_date),"%A, %B %e, %Y", :strftime) %> To  <%= Timex.format!(Date.from_iso8601!(@end_date),"%A, %B %e, %Y", :strftime) %></span>
									</div>
									<%# <div class="m-invoice__item">
										<span class="m-invoice__subtitle">INVOICE NO.</span>
										<span class="m-invoice__text">GS 000014</span>
									</div>
									<div class="m-invoice__item">
										<span class="m-invoice__subtitle">INVOICE TO.</span>
										<span class="m-invoice__text">Iris Watson, P.O. Box 283 8562 Fusce RD.<br>Fredrick Nebraska 20620</span>
									</div>  %>
								</div>
							</div>
						</div>
						<div class="m-invoice__body m-invoice__body--centered">
							<div class="table-responsive">
								<table class="table">

									<thead>
										<tr>
											<th>PERIOD</th>
											<th>STATUS</th>
											<th>COUNT</th>
										</tr>
									</thead>
									<tbody>
										<%= for {period, results} <- @delayed_wagons do %>
											<%= if period != "0-3 days" do %>
												<td>
													<%= period %>
												</td>
											<% end %>
													<%= for stat <- results  do %>
														<tr>
															<%= if period != "0-3 days" do %>
																<td></td>
																<td style="font-weight: 300; font-size: 15px;"> <%= if stat.status == "E" do %> Empty <% else %> Loaded <% end %> </td>
																<td style="font-weight: 300; font-size: 15px;"> <%= stat.count %>
																</td>
															<% end %>
														</tr>
													<% end %>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
						<div class="m-invoice__footer"    style="margin-top: 2rem;">
							<div class="m-invoice__table  m-invoice__table--centered table-responsive">
								<table class="table">
									<thead>
										<tr>
											<%= for totals <- @totals do %>
												<th><%= if totals.wagon_status == "E" do %> Empty <% else %> Loaded <% end %></th>
											<% end %>
												<th>TOTAL</th>
										</tr>
									</thead>
									<tbody>

										<tr>
											<%= for totals <- @totals do %>
												<td><%= totals.count_all %></td>
											<% end %>
											<td class="m--font-danger"><%= @grand_total %></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade model_select_2" id="date_filter">
    <div class="modal-dialog modal-lg modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle" style="margin-top:5px; margin-left:20px;">Filter</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
            </div>
            <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed col-lg-12" action="" method="POST">
                <input type="hidden" name="_csrf_token" value="<%= Plug.CSRFProtection.get_csrf_token()%>">
                <div class="m-portlet__body">

                    <div class="form-group m-form__group row">
                        <div class="col-lg-6">
                            <label>Start Date</label>
                            <div class="m-input-icon m-input-icon--right">
                                <input type="date" class="form-control m-input" name="start_date">
                            </div>
                            <span class="m-form__help">Please select Start date</span>
                        </div>
                        <div class="col-lg-6">
                            <label class="">End Date</label>
                            <div class="m-input-icon m-input-icon--right">
                                <input type="date" class="form-control m-input" name="end_date" required="required">
                            </div>
                            <span class="m-form__help">Please select End date</span>
                        </div>
                    </div>

                </div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
            </form>
        </div>
    </div>
</div>